export const CREATE_PRODUCTS = "CREATE_PRODUCTS";
export const CREATE_PRODUCTS_SUCCESS = "CREATE_PRODUCTS_SUCCESS";
export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTSS_SUCCESS";
export const UPDATE_PRODUCTS_SUCCESS = "UPDATE_PRODUCTS_SUCCESS";
export const DELETE_PRODUCTS_SUCCESS = "DELETE_PRODUCTS_SUCCESS";

export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const LOAD_CATEGORY_SUCCESS = "LOAD_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const SWITCH_ACTIVE_CATEGORY_SUCCESS="SWITCH_ACTIVE_CATEGORY_SUCCESS"
export const SWITCH_ACTIVE_PRODUCT_SUCCESS="SWITCH_ACTIVE_PRODUCT_SUCCESS"
export const LOAD_CATEGORIES_SUCCESS="LOAD_CATEGORIES_SUCCESS"


export const UPDATE_SELECTED_MENU_CATEGORY="UPDATE_SELECTED_MENU_CATEGORY"
export const UPDATE_SELECTED_CATALOGUE_CATEGORY="UPDATE_SELECTED_CATALOGUE_CATEGORY"

export const ADD_TO_SHOP_LIST="ADD_TO_SHOP_LIST"
export const DELETE_FROM_SHOP_LIST="DELETE_FROM_SHOP_LIST"
export const RESET_SHOP_LIST="RESET_SHOP_LIST"
export const ADD_ONE_TO_SHOP_LIST_WITH_INDEX="ADD_ONE_TO_SHOP_LIST_WITH_INDEX"
export const DELETE_ONE_FROM_SHOP_LIST="DELETE_ONE_FROM_SHOP_LIST"

export const ALREADY_PAYED="ALREADY_PAYED"

export const UPDATE_PAYMENT_INFO="UPDATE_PAYMENT_INFO"
export const RESET_PAYMENT_INFO="RESET_PAYMENT_INFO"


export const UPDATE_NO_TICKET="UPDATE_NO_TICKET"
export const INCREASE_NO_TICKET="INCREASE_NO_TICKET"



